version: "3.8"
services:
  # server container manages client requests
  server:
    build: ./server
    ports:
      - "9000:9000"
      # localhost:9000/ for host machine
      # server:9000/ for containers
    volumes: 
      - userdata:/storage # mounted volume, contains user generated data
  # executor container responds to requests from the server container
  executor:
    build: ./executor
    ports:
      - "8080:8080"
      # localhost:8080/ for host machine
      # executor:8080/ for containers
    volumes: 
      - userdata:/storage # mounted volume, contains user generated data
volumes:
  # userdata volume common to all composed containers
  userdata:
    external: true